### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by Hombre2014** [DelhinRharl/Leaderboard#6]
Very nice interface and fully functional leaderboard app. Great job.
I have only one suggestion. I think you do not need this line in your HTML file, since you are importing the CSS file in main.js.
https://github.com/DelhinRharl/Leaderboard/blob/c092b41d4024c37b34f917d75c28ea14e23495a2/src/myindex.html#L8

**Comment by DelhinRharl** [comment]
Thank you!
